spring:
  datasource:
      type: com.zaxxer.hikari.HikariDataSource
      url: jdbc:mysql://localhost:3306/oauth2.0?characterEncoding=utf8&useSSL=true
      username: root
      password: 123
      hikari:
        maximum-pool-size: 50
        auto-commit: false
        idle-timeout: 180000
        max-lifetime: 300000
        minimum-idle: 5